### ISSUE TITLE
There have a Dead cycle 

### ISSUE THREAD

**Issue by wuxq** [mantoufan/mtfScrollList#1]
https://github.com/mantoufan/mtfScrollList/blob/07875befdb4be2dc2631875ac8870ee0186dc34b/mtfscrolllist/src/mtfscrolllist.js#L221

**Comment by mantoufan** [comment]
The program will try to correct the rolling position when the rolling fails. 
In general, it will not trigger the dead loop.
Could you please tell me the operation of triggering the dead loop in detail? Thanks

**Comment by mantoufan** [comment]
Thanks for your feedback, we have limit the maximum number of `correct` function calls to 3 times to avoid possible dead loops
```javascript
const correct = retryTime => {
  if (retryTime > 2) return
  console.log(retryTime)
  correct((retryTime || 0) + 1)
}
```
